# Generated by Django 3.1.1 on 2020-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200919_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
