# Generated by Django 3.1.1 on 2020-09-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20200919_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='times_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
