# Generated by Django 3.1.1 on 2020-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20200920_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_real',
            field=models.BooleanField(default=False),
        ),
    ]
