# Generated by Django 3.1.1 on 2020-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_user_mail_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='method',
            field=models.CharField(default='No method', max_length=200),
            preserve_default=False,
        ),
    ]
